[package]
name = "entropy"
description = "Calculates the Shannon entropy of arrays of bytes and strings"
license = "MIT"
version = "0.2.0"
repository = "https://github.com/rmbreak/entropy"
homepage = "https://github.com/rmbreak/entropy"
authors = ["Mack Stump <mack.stump@gmail.com>"]

[dependencies]
